
quarkus:
  datasource:
    db-kind: "postgresql"

  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  rest-client:
    logging:
      scope: request-response
      body-limit: 4096
    openlibrary:
      url: "https://openlibrary.org"
      follow-redirects: true

  log:
    level: INFO
    min-level: TRACE
    category:
      "at.aau.ase.cl":
        level: DEBUG
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
    hibernate-orm:
      database:
        generation: drop-and-create
    rest-client:
      logging:
        scope: request-response
        body-limit: 16384

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: true
      username: "crowd-library"
      password: "crowd-library"
      jdbc:
        url: "jdbc:postgresql://localhost:5432/crowd-library"
    hibernate-orm:
      database:
        generation: drop-and-create
