
quarkus:
  datasource:
    db-kind: "postgresql"

  hibernate-orm:
    database:
      generation: none
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

  # see https://quarkus.io/guides/flyway
  flyway:
    enabled: true
    table: "book_schema_history"
    clean-disabled: true
    baseline-version: "0.0.1"
    baseline-at-start: true
    migrate-at-start: true

  rest-client:
    logging:
      scope: request-response
      body-limit: 4096
    openlibrary:
      url: "https://openlibrary.org"
      follow-redirects: true

  # see https://quarkus.io/guides/openapi-swaggerui
  smallrye-openapi:
    store-schema-directory: "target/openapi"
    store-schema-file-name: "book-service.yaml"
  swagger-ui:
    always-include: true
    path: "/docs"
    query-config-enabled: true

  # see https://quarkus.io/guides/container-image#customizing
  container-image:
    group: "AAU-ASE24W-group-E"

  # see https://quarkus.io/guides/logging#configuration
  log:
    level: INFO
    min-level: TRACE
    category:
      "at.aau.ase.cl":
        level: DEBUG
      "org.jboss.resteasy.reactive.client.logging":
        level: DEBUG

"%test":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: false
      username: "crowd-library"
      password: "crowd-library"
      jdbc:
        url: "jdbc:postgresql://localhost:5432/crowd-library"
    hibernate-orm:
      database:
        generation: drop-and-create
    flyway:
      # in %test we drop-and-create the database, thus, migration is neither needed nor possible
      migrate-at-start: false
    rest-client:
      logging:
        scope: request-response
        body-limit: 16384

"%dev":
  quarkus:
    datasource:
      devservices:
        enabled: true
        reuse: true
      username: "crowd-library"
      password: "crowd-library"
      jdbc:
        url: "jdbc:postgresql://localhost:5432/crowd-library"
    hibernate-orm:
      database:
        generation: drop-and-create
