package at.aau.ase.cl.api.model;

import org.eclipse.microprofile.openapi.annotations.media.Schema;

import java.util.UUID;

public record BookOwner(
        @Schema(readOnly = true, description = "Unique identifier of the book owner, generated by user-service")
        UUID id,

        @Schema(description = "Display name of the book owner")
        String name,

        @Schema(description = "Latitude part of the location of the book owner")
        Double latitude,

        @Schema(description = "Longitude part of the location of the book owner")
        Double longitude
) {
}
